// This is auto-generated by scripts/downloadReleases.js
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.supportedReleases = [
        "3.7.5",
        "3.6.3",
        "3.5.1",
        "3.3.3",
        "3.1.6",
        "3.0.1",
        "2.8.1",
        "2.7.2",
        "2.4.1"
    ];
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVsZWFzZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9zYW5kYm94L3NyYy9yZWxlYXNlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSx3REFBd0Q7Ozs7SUFFM0MsUUFBQSxpQkFBaUIsR0FBRztRQUMvQixPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87S0FDQyxDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiLy8gVGhpcyBpcyBhdXRvLWdlbmVyYXRlZCBieSBzY3JpcHRzL2Rvd25sb2FkUmVsZWFzZXMuanNcblxuZXhwb3J0IGNvbnN0IHN1cHBvcnRlZFJlbGVhc2VzID0gW1xuICBcIjMuNy41XCIsXG4gIFwiMy42LjNcIixcbiAgXCIzLjUuMVwiLFxuICBcIjMuMy4zXCIsXG4gIFwiMy4xLjZcIixcbiAgXCIzLjAuMVwiLFxuICBcIjIuOC4xXCIsXG4gIFwiMi43LjJcIixcbiAgXCIyLjQuMVwiXG5dIGFzIGNvbnN0O1xuXG5leHBvcnQgdHlwZSBSZWxlYXNlVmVyc2lvbnMgPVxuICB8IFwiMy43LjVcIlxuICB8IFwiMy42LjNcIlxuICB8IFwiMy41LjFcIlxuICB8IFwiMy4zLjNcIlxuICB8IFwiMy4xLjZcIlxuICB8IFwiMy4wLjFcIlxuICB8IFwiMi44LjFcIlxuICB8IFwiMi43LjJcIlxuICB8IFwiMi40LjFcIjtcbiJdfQ==