export declare const createConfigDropdown: (sandbox: {
    config: {
        text: string;
        useJavaScript: boolean;
        compilerOptions: import("monaco-editor").languages.typescript.CompilerOptions;
        monacoSettings?: import("monaco-editor").editor.IEditorOptions | undefined;
        acquireTypes: boolean;
        supportTwoslashCompilerOptions: boolean;
        suppressAutomaticallyGettingDefaultText?: true | undefined;
        suppressAutomaticallyGettingCompilerFlags?: true | undefined;
        logger: {
            log: (...args: any[]) => void;
            error: (...args: any[]) => void;
        };
        domID: string;
    };
    supportedVersions: readonly ["3.7.5", "3.6.3", "3.5.1", "3.3.3", "3.1.6", "3.0.1", "2.8.1", "2.7.2", "2.4.1"];
    editor: import("monaco-editor").editor.IStandaloneCodeEditor;
    language: string;
    monaco: typeof import("monaco-editor");
    getWorkerProcess: () => Promise<import("typescriptlang-org/static/js/sandbox/tsWorker").TypeScriptWorker>;
    tsvfs: typeof import("typescriptlang-org/static/js/sandbox/vendor/typescript-vfs");
    getEmitResult: () => Promise<import("typescript").EmitOutput>;
    getRunnableJS: () => Promise<string>;
    getDTSForCode: () => Promise<string>;
    getDomNode: () => HTMLElement;
    getModel: () => import("monaco-editor").editor.ITextModel;
    getText: () => string;
    setText: (text: string) => void;
    getAST: () => Promise<import("typescript").SourceFile>;
    ts: typeof import("typescript");
    createTSProgram: () => Promise<import("typescript").Program>;
    compilerDefaults: import("monaco-editor").languages.typescript.CompilerOptions;
    getCompilerOptions: () => import("monaco-editor").languages.typescript.CompilerOptions;
    setCompilerSettings: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void;
    updateCompilerSetting: (key: string | number, value: any) => void;
    updateCompilerSettings: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void;
    setDidUpdateCompilerSettings: (func: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void) => void;
    lzstring: typeof import("typescriptlang-org/static/js/sandbox/vendor/lzstring.min");
    getURLQueryWithCompilerOptions: (sandbox: any, paramOverrides?: any) => string;
    getTwoSlashComplierOptions: (code: string) => any;
    languageServiceDefaults: import("monaco-editor").languages.typescript.LanguageServiceDefaults;
}, monaco: typeof import("monaco-editor")) => void;
export declare const updateConfigDropdownForCompilerOptions: (sandbox: {
    config: {
        text: string;
        useJavaScript: boolean;
        compilerOptions: import("monaco-editor").languages.typescript.CompilerOptions;
        monacoSettings?: import("monaco-editor").editor.IEditorOptions | undefined;
        acquireTypes: boolean;
        supportTwoslashCompilerOptions: boolean;
        suppressAutomaticallyGettingDefaultText?: true | undefined;
        suppressAutomaticallyGettingCompilerFlags?: true | undefined;
        logger: {
            log: (...args: any[]) => void;
            error: (...args: any[]) => void;
        };
        domID: string;
    };
    supportedVersions: readonly ["3.7.5", "3.6.3", "3.5.1", "3.3.3", "3.1.6", "3.0.1", "2.8.1", "2.7.2", "2.4.1"];
    editor: import("monaco-editor").editor.IStandaloneCodeEditor;
    language: string;
    monaco: typeof import("monaco-editor");
    getWorkerProcess: () => Promise<import("typescriptlang-org/static/js/sandbox/tsWorker").TypeScriptWorker>;
    tsvfs: typeof import("typescriptlang-org/static/js/sandbox/vendor/typescript-vfs");
    getEmitResult: () => Promise<import("typescript").EmitOutput>;
    getRunnableJS: () => Promise<string>;
    getDTSForCode: () => Promise<string>;
    getDomNode: () => HTMLElement;
    getModel: () => import("monaco-editor").editor.ITextModel;
    getText: () => string;
    setText: (text: string) => void;
    getAST: () => Promise<import("typescript").SourceFile>;
    ts: typeof import("typescript");
    createTSProgram: () => Promise<import("typescript").Program>;
    compilerDefaults: import("monaco-editor").languages.typescript.CompilerOptions;
    getCompilerOptions: () => import("monaco-editor").languages.typescript.CompilerOptions;
    setCompilerSettings: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void;
    updateCompilerSetting: (key: string | number, value: any) => void;
    updateCompilerSettings: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void;
    setDidUpdateCompilerSettings: (func: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void) => void;
    lzstring: typeof import("typescriptlang-org/static/js/sandbox/vendor/lzstring.min");
    getURLQueryWithCompilerOptions: (sandbox: any, paramOverrides?: any) => string;
    getTwoSlashComplierOptions: (code: string) => any;
    languageServiceDefaults: import("monaco-editor").languages.typescript.LanguageServiceDefaults;
}, monaco: typeof import("monaco-editor")) => void;
export declare const setupJSONToggleForConfig: (sandbox: {
    config: {
        text: string;
        useJavaScript: boolean;
        compilerOptions: import("monaco-editor").languages.typescript.CompilerOptions;
        monacoSettings?: import("monaco-editor").editor.IEditorOptions | undefined;
        acquireTypes: boolean;
        supportTwoslashCompilerOptions: boolean;
        suppressAutomaticallyGettingDefaultText?: true | undefined;
        suppressAutomaticallyGettingCompilerFlags?: true | undefined;
        logger: {
            log: (...args: any[]) => void;
            error: (...args: any[]) => void;
        };
        domID: string;
    };
    supportedVersions: readonly ["3.7.5", "3.6.3", "3.5.1", "3.3.3", "3.1.6", "3.0.1", "2.8.1", "2.7.2", "2.4.1"];
    editor: import("monaco-editor").editor.IStandaloneCodeEditor;
    language: string;
    monaco: typeof import("monaco-editor");
    getWorkerProcess: () => Promise<import("typescriptlang-org/static/js/sandbox/tsWorker").TypeScriptWorker>;
    tsvfs: typeof import("typescriptlang-org/static/js/sandbox/vendor/typescript-vfs");
    getEmitResult: () => Promise<import("typescript").EmitOutput>;
    getRunnableJS: () => Promise<string>;
    getDTSForCode: () => Promise<string>;
    getDomNode: () => HTMLElement;
    getModel: () => import("monaco-editor").editor.ITextModel;
    getText: () => string;
    setText: (text: string) => void;
    getAST: () => Promise<import("typescript").SourceFile>;
    ts: typeof import("typescript");
    createTSProgram: () => Promise<import("typescript").Program>;
    compilerDefaults: import("monaco-editor").languages.typescript.CompilerOptions;
    getCompilerOptions: () => import("monaco-editor").languages.typescript.CompilerOptions;
    setCompilerSettings: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void;
    updateCompilerSetting: (key: string | number, value: any) => void;
    updateCompilerSettings: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void;
    setDidUpdateCompilerSettings: (func: (opts: import("monaco-editor").languages.typescript.CompilerOptions) => void) => void;
    lzstring: typeof import("typescriptlang-org/static/js/sandbox/vendor/lzstring.min");
    getURLQueryWithCompilerOptions: (sandbox: any, paramOverrides?: any) => string;
    getTwoSlashComplierOptions: (code: string) => any;
    languageServiceDefaults: import("monaco-editor").languages.typescript.LanguageServiceDefaults;
}) => void;
